import { createElement } from 'lwc';
import Componente04TelaTotalPaisEFilhos from 'c/componente04TelaTotalPaisEFilhos';

describe('c-componente04-tela-total-pais-e-filhos', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-componente04-tela-total-pais-e-filhos', {
            is: Componente04TelaTotalPaisEFilhos
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});